server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-lesson?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
